[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "edit-summaries"
version = "0.0.1"
dependencies = [
]

[project.scripts]
extract-comments = "load.extract_comments:main"
load-comments = "load.load_comments:main"
